// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type AppConfig struct {
	Key       string
	Value     string
	UpdatedAt string
}

type CacheItem struct {
	Namespace string
	Key       string
	Payload   string
	ExpiresAt sql.NullString
	UpdatedAt string
}

type Episode struct {
	ID            int64
	ShowID        int64
	SeasonID      int64
	EpisodeNumber int64
	Title         string
	Watched       int64
	AddedAt       string
}

type Movie struct {
	ID          int64
	Title       string
	ReleaseYear int64
	Watched     int64
	AddedAt     string
}

type Season struct {
	ID           int64
	ShowID       int64
	SeasonNumber int64
	Title        string
}

type Show struct {
	ID        int64
	Title     string
	Summary   string
	AddedAt   string
	UpdatedAt string
}
