// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const countShows = `-- name: CountShows :one
SELECT COUNT(*)
FROM shows
`

func (q *Queries) CountShows(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countShows)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredCacheItems = `-- name: DeleteExpiredCacheItems :exec
DELETE FROM cache_items
WHERE expires_at IS NOT NULL AND expires_at <= ?
`

func (q *Queries) DeleteExpiredCacheItems(ctx context.Context, expiresAt sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredCacheItems, expiresAt)
	return err
}

const getCacheItem = `-- name: GetCacheItem :one
SELECT namespace, key, payload, expires_at, updated_at
FROM cache_items
WHERE namespace = ? AND key = ?
`

type GetCacheItemParams struct {
	Namespace string
	Key       string
}

func (q *Queries) GetCacheItem(ctx context.Context, arg GetCacheItemParams) (CacheItem, error) {
	row := q.db.QueryRowContext(ctx, getCacheItem, arg.Namespace, arg.Key)
	var i CacheItem
	err := row.Scan(
		&i.Namespace,
		&i.Key,
		&i.Payload,
		&i.ExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConfig = `-- name: GetConfig :one
SELECT key, value, updated_at
FROM app_config
WHERE key = ?
`

func (q *Queries) GetConfig(ctx context.Context, key string) (AppConfig, error) {
	row := q.db.QueryRowContext(ctx, getConfig, key)
	var i AppConfig
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const getSeason = `-- name: GetSeason :one
SELECT id, show_id, season_number, title
FROM seasons
WHERE id = ?
`

func (q *Queries) GetSeason(ctx context.Context, id int64) (Season, error) {
	row := q.db.QueryRowContext(ctx, getSeason, id)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.ShowID,
		&i.SeasonNumber,
		&i.Title,
	)
	return i, err
}

const getShow = `-- name: GetShow :one
SELECT id, title, summary, added_at, updated_at
FROM shows
WHERE id = ?
`

func (q *Queries) GetShow(ctx context.Context, id int64) (Show, error) {
	row := q.db.QueryRowContext(ctx, getShow, id)
	var i Show
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertConfigIfNotExists = `-- name: InsertConfigIfNotExists :exec
INSERT OR IGNORE INTO app_config (key, value, updated_at)
VALUES (?, ?, ?)
`

type InsertConfigIfNotExistsParams struct {
	Key       string
	Value     string
	UpdatedAt string
}

func (q *Queries) InsertConfigIfNotExists(ctx context.Context, arg InsertConfigIfNotExistsParams) error {
	_, err := q.db.ExecContext(ctx, insertConfigIfNotExists, arg.Key, arg.Value, arg.UpdatedAt)
	return err
}

const insertEpisode = `-- name: InsertEpisode :exec
INSERT INTO episodes (id, show_id, season_id, episode_number, title, watched, added_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertEpisodeParams struct {
	ID            int64
	ShowID        int64
	SeasonID      int64
	EpisodeNumber int64
	Title         string
	Watched       int64
	AddedAt       string
}

func (q *Queries) InsertEpisode(ctx context.Context, arg InsertEpisodeParams) error {
	_, err := q.db.ExecContext(ctx, insertEpisode,
		arg.ID,
		arg.ShowID,
		arg.SeasonID,
		arg.EpisodeNumber,
		arg.Title,
		arg.Watched,
		arg.AddedAt,
	)
	return err
}

const insertMovie = `-- name: InsertMovie :exec
INSERT INTO movies (id, title, release_year, watched, added_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertMovieParams struct {
	ID          int64
	Title       string
	ReleaseYear int64
	Watched     int64
	AddedAt     string
}

func (q *Queries) InsertMovie(ctx context.Context, arg InsertMovieParams) error {
	_, err := q.db.ExecContext(ctx, insertMovie,
		arg.ID,
		arg.Title,
		arg.ReleaseYear,
		arg.Watched,
		arg.AddedAt,
	)
	return err
}

const insertSeason = `-- name: InsertSeason :exec
INSERT INTO seasons (id, show_id, season_number, title)
VALUES (?, ?, ?, ?)
`

type InsertSeasonParams struct {
	ID           int64
	ShowID       int64
	SeasonNumber int64
	Title        string
}

func (q *Queries) InsertSeason(ctx context.Context, arg InsertSeasonParams) error {
	_, err := q.db.ExecContext(ctx, insertSeason,
		arg.ID,
		arg.ShowID,
		arg.SeasonNumber,
		arg.Title,
	)
	return err
}

const insertShow = `-- name: InsertShow :exec
INSERT INTO shows (id, title, summary, added_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertShowParams struct {
	ID        int64
	Title     string
	Summary   string
	AddedAt   string
	UpdatedAt string
}

func (q *Queries) InsertShow(ctx context.Context, arg InsertShowParams) error {
	_, err := q.db.ExecContext(ctx, insertShow,
		arg.ID,
		arg.Title,
		arg.Summary,
		arg.AddedAt,
		arg.UpdatedAt,
	)
	return err
}

const listConfigs = `-- name: ListConfigs :many
SELECT key, value, updated_at
FROM app_config
ORDER BY key
`

func (q *Queries) ListConfigs(ctx context.Context) ([]AppConfig, error) {
	rows, err := q.db.QueryContext(ctx, listConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppConfig
	for rows.Next() {
		var i AppConfig
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodesBySeason = `-- name: ListEpisodesBySeason :many
SELECT
  e.id,
  e.show_id,
  e.season_id,
  sn.season_number,
  e.episode_number,
  e.title,
  e.watched,
  e.added_at,
  CASE
    WHEN e.id = (
      SELECT e2.id
      FROM episodes e2
      JOIN seasons sn2 ON sn2.id = e2.season_id
      WHERE e2.show_id = e.show_id AND e2.watched = 0
      ORDER BY sn2.season_number, e2.episode_number
      LIMIT 1
    ) THEN 1
    ELSE 0
  END AS is_next_up
FROM episodes e
JOIN seasons sn ON sn.id = e.season_id
WHERE e.season_id = ?
ORDER BY e.episode_number
`

type ListEpisodesBySeasonRow struct {
	ID            int64
	ShowID        int64
	SeasonID      int64
	SeasonNumber  int64
	EpisodeNumber int64
	Title         string
	Watched       int64
	AddedAt       string
	IsNextUp      int64
}

func (q *Queries) ListEpisodesBySeason(ctx context.Context, seasonID int64) ([]ListEpisodesBySeasonRow, error) {
	rows, err := q.db.QueryContext(ctx, listEpisodesBySeason, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEpisodesBySeasonRow
	for rows.Next() {
		var i ListEpisodesBySeasonRow
		if err := rows.Scan(
			&i.ID,
			&i.ShowID,
			&i.SeasonID,
			&i.SeasonNumber,
			&i.EpisodeNumber,
			&i.Title,
			&i.Watched,
			&i.AddedAt,
			&i.IsNextUp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovies = `-- name: ListMovies :many
SELECT id, title, release_year, watched, added_at
FROM movies
ORDER BY added_at DESC, id DESC
`

func (q *Queries) ListMovies(ctx context.Context) ([]Movie, error) {
	rows, err := q.db.QueryContext(ctx, listMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ReleaseYear,
			&i.Watched,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentlyAdded = `-- name: ListRecentlyAdded :many
SELECT item_type, item_id, headline, subline, added_at
FROM (
  SELECT
    'movie' AS item_type,
    m.id AS item_id,
    m.title AS headline,
    printf('%d', m.release_year) AS subline,
    m.added_at AS added_at
  FROM movies m

  UNION ALL

  SELECT
    'episode' AS item_type,
    e.id AS item_id,
    sh.title || ' ' || printf('S%02dE%02d', sn.season_number, e.episode_number) AS headline,
    e.title AS subline,
    e.added_at AS added_at
  FROM episodes e
  JOIN seasons sn ON sn.id = e.season_id
  JOIN shows sh ON sh.id = e.show_id
) items
ORDER BY added_at DESC
LIMIT ?
`

type ListRecentlyAddedRow struct {
	ItemType string
	ItemID   int64
	Headline string
	Subline  sql.NullString
	AddedAt  string
}

func (q *Queries) ListRecentlyAdded(ctx context.Context, limit int64) ([]ListRecentlyAddedRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentlyAdded, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentlyAddedRow
	for rows.Next() {
		var i ListRecentlyAddedRow
		if err := rows.Scan(
			&i.ItemType,
			&i.ItemID,
			&i.Headline,
			&i.Subline,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasonsByShow = `-- name: ListSeasonsByShow :many
SELECT
  sn.id,
  sn.show_id,
  sn.season_number,
  sn.title,
  CAST(COALESCE(SUM(CASE WHEN e.watched = 1 THEN 1 ELSE 0 END), 0) AS INTEGER) AS watched_count,
  CAST(COALESCE(COUNT(e.id), 0) AS INTEGER) AS total_episodes
FROM seasons sn
LEFT JOIN episodes e ON e.season_id = sn.id
WHERE sn.show_id = ?
GROUP BY sn.id, sn.show_id, sn.season_number, sn.title
ORDER BY sn.season_number
`

type ListSeasonsByShowRow struct {
	ID            int64
	ShowID        int64
	SeasonNumber  int64
	Title         string
	WatchedCount  int64
	TotalEpisodes int64
}

func (q *Queries) ListSeasonsByShow(ctx context.Context, showID int64) ([]ListSeasonsByShowRow, error) {
	rows, err := q.db.QueryContext(ctx, listSeasonsByShow, showID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeasonsByShowRow
	for rows.Next() {
		var i ListSeasonsByShowRow
		if err := rows.Scan(
			&i.ID,
			&i.ShowID,
			&i.SeasonNumber,
			&i.Title,
			&i.WatchedCount,
			&i.TotalEpisodes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTVShows = `-- name: ListTVShows :many
SELECT
  s.id,
  s.title,
  CAST(COALESCE(SUM(CASE WHEN e.watched = 1 THEN 1 ELSE 0 END), 0) AS INTEGER) AS watched_count,
  CAST(COALESCE(COUNT(e.id), 0) AS INTEGER) AS total_episodes,
  CAST(COALESCE((
    SELECT sn.season_number
    FROM episodes e2
    JOIN seasons sn ON sn.id = e2.season_id
    WHERE e2.show_id = s.id AND e2.watched = 0
    ORDER BY sn.season_number, e2.episode_number
    LIMIT 1
  ), 0) AS INTEGER) AS next_up_season,
  CAST(COALESCE((
    SELECT e2.episode_number
    FROM episodes e2
    JOIN seasons sn ON sn.id = e2.season_id
    WHERE e2.show_id = s.id AND e2.watched = 0
    ORDER BY sn.season_number, e2.episode_number
    LIMIT 1
  ), 0) AS INTEGER) AS next_up_episode,
  CAST(COALESCE((
    SELECT e2.title
    FROM episodes e2
    JOIN seasons sn ON sn.id = e2.season_id
    WHERE e2.show_id = s.id AND e2.watched = 0
    ORDER BY sn.season_number, e2.episode_number
    LIMIT 1
  ), '') AS TEXT) AS next_up_title
FROM shows s
LEFT JOIN episodes e ON e.show_id = s.id
GROUP BY s.id, s.title
ORDER BY s.title
`

type ListTVShowsRow struct {
	ID            int64
	Title         string
	WatchedCount  int64
	TotalEpisodes int64
	NextUpSeason  int64
	NextUpEpisode int64
	NextUpTitle   string
}

func (q *Queries) ListTVShows(ctx context.Context) ([]ListTVShowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTVShows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTVShowsRow
	for rows.Next() {
		var i ListTVShowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.WatchedCount,
			&i.TotalEpisodes,
			&i.NextUpSeason,
			&i.NextUpEpisode,
			&i.NextUpTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCacheItem = `-- name: UpsertCacheItem :exec
INSERT INTO cache_items (namespace, key, payload, expires_at, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(namespace, key)
DO UPDATE SET
  payload = excluded.payload,
  expires_at = excluded.expires_at,
  updated_at = excluded.updated_at
`

type UpsertCacheItemParams struct {
	Namespace string
	Key       string
	Payload   string
	ExpiresAt sql.NullString
	UpdatedAt string
}

func (q *Queries) UpsertCacheItem(ctx context.Context, arg UpsertCacheItemParams) error {
	_, err := q.db.ExecContext(ctx, upsertCacheItem,
		arg.Namespace,
		arg.Key,
		arg.Payload,
		arg.ExpiresAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertConfig = `-- name: UpsertConfig :exec
INSERT INTO app_config (key, value, updated_at)
VALUES (?, ?, ?)
ON CONFLICT(key)
DO UPDATE SET
  value = excluded.value,
  updated_at = excluded.updated_at
`

type UpsertConfigParams struct {
	Key       string
	Value     string
	UpdatedAt string
}

func (q *Queries) UpsertConfig(ctx context.Context, arg UpsertConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertConfig, arg.Key, arg.Value, arg.UpdatedAt)
	return err
}
